version: "3.9"
services:
  beers_api:
    build: .
    image: app/beers-api
    container_name: beers-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql:5.7.22
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "beers_db"
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3307:3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
